-- ============================================================
-- Migration 001 — QR Codes + Activity Logs
-- Run in Supabase SQL Editor (project: psblyvwfbgmwyrtzoyhz)
--
-- SAFE: Uses CREATE TABLE IF NOT EXISTS / CREATE INDEX IF NOT EXISTS
-- Does NOT alter or drop any existing tables.
-- Pre-checks: responder_activity already exists (untouched).
--             qr_codes and activity_logs do NOT exist yet.
-- ============================================================

-- ─── QR CODES ─────────────────────────────────────────────────────────────────
-- Stores server-issued QR tokens bound to a user.
-- Tokens are UUID strings generated by PostgreSQL at INSERT time.
CREATE TABLE IF NOT EXISTS qr_codes (
  id          BIGSERIAL     PRIMARY KEY,
  user_id     BIGINT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  qr_token    TEXT          NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
  status      TEXT          NOT NULL DEFAULT 'active'
                            CHECK (status IN ('active', 'revoked')),
  affiliation TEXT,
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_qr_codes_user_id  ON qr_codes(user_id);
CREATE INDEX IF NOT EXISTS idx_qr_codes_token    ON qr_codes(qr_token);

-- ─── ACTIVITY LOGS ────────────────────────────────────────────────────────────
-- General-purpose audit log for all user actions across the system.
-- Complements responder_activity (responder-specific points/incidents log).
-- entity_type: 'qr_scan' | 'profile' | 'training' | 'incident' | etc.
-- entity_id:   refers to the PK of the touched record (nullable).
CREATE TABLE IF NOT EXISTS activity_logs (
  id          BIGSERIAL     PRIMARY KEY,
  user_id     BIGINT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  action      TEXT          NOT NULL,
  entity_type TEXT,
  entity_id   BIGINT,
  metadata    JSONB,
  ip_address  TEXT,
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id ON activity_logs(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_action  ON activity_logs(action);
