<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\User;

class AssetSeeder extends Seeder
{
    public function run()
    {
        DB::table('assets')->truncate();

        $creator = User::where('role', 'logistics')->orWhere('role', 'admin')->first();
        if (! $creator) {
            $this->command->error('AssetSeeder: no suitable creator user found (logistics/admin). Skipping.');
            return;
        }

        $assets = [
            [
                'asset_code' => 'AST-REF-001',
                'type' => 'Refrigerated Van',
                'category' => 'Cold Chain Transport',
                'capacity' => '1,200 liters',
                'status' => 'Standby',
                'location' => 'DOH Central Warehouse, Quezon City',
                'personnel' => null,
                'last_maintenance' => '2025-10-15',
                'next_maintenance' => '2026-04-15',
                'condition' => 'Excellent',
                'manufacturer' => 'Isuzu',
                'model' => 'NPR 4x2 Reefer',
                'year' => 2024,
                'plate_number' => 'NCR-1001',
                'mileage' => '18,450 km',
                'current_fuel_level' => 92,
                'operating_hours' => null,
                'power_source' => null,
                'setup_time' => null,
                'flight_time' => null,
                'capabilities' => json_encode(['cold_chain', 'general']), // lowercase
                'value' => '4850000.00',
                'purchase_date' => '2024-03-20',
                'created_by' => $creator->id,
                'latitude' => 14.676208,
                'longitude' => 121.043861,
            ],
            [
                'asset_code' => 'AST-AMB-002',
                'type' => 'Standard Ambulance Van',
                'category' => 'General Transport',
                'capacity' => '8 patients',
                'status' => 'Operational',
                'location' => 'DOH Region IV-A Depot',
                'personnel' => null,
                'last_maintenance' => null,
                'next_maintenance' => null,
                'condition' => null,
                'manufacturer' => null,
                'model' => 'Toyota HiAce',
                'year' => null,
                'plate_number' => 'CAL-4002',
                'mileage' => null,
                'current_fuel_level' => 78,
                'operating_hours' => null,
                'power_source' => null,
                'setup_time' => null,
                'flight_time' => null,
                'capabilities' => json_encode(['general']), // lowercase
                'value' => '2450000.00',
                'purchase_date' => null,
                'created_by' => $creator->id,
                'latitude' => 14.5995,
                'longitude' => 121.0583,
            ],
            [
                'asset_code' => 'AST-SEC-003',
                'type' => 'Armored Transport Van',
                'category' => 'High Value Transport',
                'capacity' => '500 kg',
                'status' => 'Standby',
                'location' => 'PNP-DOH Joint Depot',
                'personnel' => null,
                'last_maintenance' => null,
                'next_maintenance' => null,
                'condition' => null,
                'manufacturer' => null,
                'model' => 'Ford Transit',
                'year' => null,
                'plate_number' => 'NCR-9003',
                'mileage' => null,
                'current_fuel_level' => 65,
                'operating_hours' => null,
                'power_source' => null,
                'setup_time' => null,
                'flight_time' => null,
                'capabilities' => json_encode(['high_value', 'narcotics', 'general']), // Use 'high_value' not 'armored'
                'value' => '8900000.00',
                'purchase_date' => null,
                'created_by' => $creator->id,
                'latitude' => 14.6374,
                'longitude' => 121.0672,
            ],
            [
                'asset_code' => 'AST-REF-004',
                'type' => 'Refrigerated Truck',
                'category' => 'Cold Chain Transport',
                'capacity' => '3,500 liters',
                'status' => 'Standby',
                'location' => 'DOH Region VII, Cebu',
                'personnel' => null,
                'last_maintenance' => null,
                'next_maintenance' => null,
                'condition' => null,
                'manufacturer' => null,
                'model' => 'Hino 500',
                'year' => null,
                'plate_number' => 'CEB-7004',
                'mileage' => null,
                'current_fuel_level' => 100,
                'operating_hours' => null,
                'power_source' => null,
                'setup_time' => null,
                'flight_time' => null,
                'capabilities' => json_encode(['cold_chain']), // lowercase
                'value' => '7200000.00',
                'purchase_date' => null,
                'created_by' => $creator->id,
                'latitude' => 10.3157,
                'longitude' => 123.8854,
            ],
            [
                'asset_code' => 'AST-GEN-001',
                'type' => 'Mobile Generator',
                'category' => 'Power Supply',
                'capacity' => '150 kVA',
                'status' => 'Operational',
                'location' => 'DOH National Center',
                'personnel' => null,
                'last_maintenance' => null,
                'next_maintenance' => null,
                'condition' => null,
                'manufacturer' => null,
                'model' => null,
                'year' => null,
                'plate_number' => null,
                'mileage' => null,
                'current_fuel_level' => null,
                'operating_hours' => '3,240 hrs',
                'power_source' => 'Diesel',
                'setup_time' => '45 minutes',
                'flight_time' => null,
                'capabilities' => json_encode(['general']), // lowercase
                'value' => '4150000.00',
                'purchase_date' => null,
                'created_by' => $creator->id,
                'latitude' => 14.5822,
                'longitude' => 120.9825,
            ],
            [
                'asset_code' => 'AST-PTV-005',
                'type' => 'Patient Transport Van',
                'category' => 'General Transport',
                'capacity' => '6 patients',
                'status' => 'Operational',
                'location' => 'DOH Region X',
                'personnel' => null,
                'last_maintenance' => '2025-01-10',
                'next_maintenance' => '2025-06-10',
                'condition' => 'Fair',
                'manufacturer' => null,
                'model' => 'Nissan Urvan',
                'year' => null,
                'plate_number' => 'NOR-3005',
                'mileage' => null,
                'current_fuel_level' => 34,
                'operating_hours' => null,
                'power_source' => null,
                'setup_time' => null,
                'flight_time' => null,
                'capabilities' => json_encode(['general']), // lowercase
                'value' => '1850000.00',
                'purchase_date' => null,
                'created_by' => $creator->id,
                'latitude' => 8.4542,
                'longitude' => 124.6319,
            ],
              [
                'asset_code' => 'AST-DRN-006',
                'type' => 'Drone Surveillance Unit',
                'category' => 'High Value Transport',
                'capacity' => 'Payload 50 kg',
                'status' => 'Under Repair',
                'location' => 'DOH Region XI, Davao',
                'personnel' => null,
                'last_maintenance' => '2025-09-01',
                'next_maintenance' => '2026-01-01',
                'condition' => 'Poor',
                'manufacturer' => 'DJI',
                'model' => 'Matrice 600',
                'year' => 2023,
                'plate_number' => null,
                'mileage' => null,
                'current_fuel_level' => null,
                'operating_hours' => '1,200 hrs',
                'power_source' => 'Battery',
                'setup_time' => '15 minutes',
                'flight_time' => '45 minutes',
                'capabilities' => json_encode(['high_value', 'general']),
                'value' => '3500000.00',
                'purchase_date' => '2023-07-15',
                'created_by' => $creator->id,
                'latitude' => 7.1907,
                'longitude' => 125.4553,
            ],
            [
                'asset_code' => 'AST-WTR-007',
                'type' => 'Water Tanker Truck',
                'category' => 'General Transport',
                'capacity' => '10,000 liters',
                'status' => 'Decommissioned',
                'location' => 'DOH Region II, Tuguegarao',
                'personnel' => null,
                'last_maintenance' => '2024-12-01',
                'next_maintenance' => null,
                'condition' => 'Fair',
                'manufacturer' => 'MAN',
                'model' => 'TGS 26.400',
                'year' => 2018,
                'plate_number' => 'CAG-7007',
                'mileage' => '120,000 km',
                'current_fuel_level' => 0,
                'operating_hours' => null,
                'power_source' => 'Diesel',
                'setup_time' => null,
                'flight_time' => null,
                'capabilities' => json_encode(['general']),
                'value' => '1500000.00',
                'purchase_date' => '2018-05-10',
                'created_by' => $creator->id,
                'latitude' => 17.6131,
                'longitude' => 121.7269,
            ],
            [
                'asset_code' => 'AST-GEN-008',
                'type' => 'Portable Generator',
                'category' => 'Power Supply',
                'capacity' => '50 kVA',
                'status' => 'Standby',
                'location' => 'DOH Region V, Legazpi',
                'personnel' => null,
                'last_maintenance' => '2025-06-20',
                'next_maintenance' => '2026-01-20',
                'condition' => 'Good',
                'manufacturer' => 'Honda',
                'model' => 'EG6500',
                'year' => 2022,
                'plate_number' => null,
                'mileage' => null,
                'current_fuel_level' => null,
                'operating_hours' => '500 hrs',
                'power_source' => 'Gasoline',
                'setup_time' => '20 minutes',
                'flight_time' => null,
                'capabilities' => json_encode(['general']),
                'value' => '750000.00',
                'purchase_date' => '2022-11-05',
                'created_by' => $creator->id,
                'latitude' => 13.1339,
                'longitude' => 123.7438,
            ],
            [
    'asset_code' => 'AST-HEL-009',
    'type' => 'Medical Helicopter',
    'category' => 'General Transport',
    'capacity' => '4 patients',
    'status' => 'Under Repair',
    'location' => 'DOH Region VIII, Tacloban',
    'personnel' => null,
    'last_maintenance' => '2025-07-12',
    'next_maintenance' => '2026-01-12',
    'condition' => 'Excellent',
    'manufacturer' => 'Airbus',
    'model' => 'H145',
    'year' => 2023,
    'plate_number' => null,
    'mileage' => null,
    'current_fuel_level' => 80,
    'operating_hours' => '600 hrs',
    'power_source' => 'Aviation Fuel',
    'setup_time' => '30 minutes',
    'flight_time' => '2 hours',
    'capabilities' => json_encode(['general', 'high_value']),
    'value' => '25000000.00',
    'purchase_date' => '2023-09-01',
    'created_by' => $creator->id,
    'latitude' => 11.2433,
    'longitude' => 125.0033,
],
[
    'asset_code' => 'AST-TRN-010',
    'type' => 'Mobile Training Van',
    'category' => 'Power Supply',
    'capacity' => 'Computer Lab – 20 seats',
    'status' => 'Under Repair',
    'location' => 'DOH Region III, Pampanga',
    'personnel' => null,
    'last_maintenance' => '2025-11-01',
    'next_maintenance' => '2026-02-01',
    'condition' => 'Poor',
    'manufacturer' => 'Mercedes-Benz',
    'model' => 'Sprinter',
    'year' => 2020,
    'plate_number' => 'PAM-1010',
    'mileage' => '85,000 km',
    'current_fuel_level' => 45,
    'operating_hours' => null,
    'power_source' => 'Diesel',
    'setup_time' => '1 hour',
    'flight_time' => null,
    'capabilities' => json_encode(['general']),
    'value' => '3500000.00',
    'purchase_date' => '2020-06-15',
    'created_by' => $creator->id,
    'latitude' => 15.0794,
    'longitude' => 120.6194,
],
[
    'asset_code' => 'AST-BOT-011',
    'type' => 'Medical Supply Boat',
    'category' => 'Cold Chain Transport',
    'capacity' => '20,000 liters',
    'status' => 'Decommissioned',
    'location' => 'DOH Region IX, Zamboanga',
    'personnel' => null,
    'last_maintenance' => '2024-05-20',
    'next_maintenance' => null,
    'condition' => 'Fair',
    'manufacturer' => 'Yamaha',
    'model' => 'SupplyCat 200',
    'year' => 2015,
    'plate_number' => null,
    'mileage' => null,
    'current_fuel_level' => 0,
    'operating_hours' => '12,000 hrs',
    'power_source' => 'Diesel',
    'setup_time' => null,
    'flight_time' => null,
    'capabilities' => json_encode(['cold_chain']),
    'value' => '5000000.00',
    'purchase_date' => '2015-03-10',
    'created_by' => $creator->id,
    'latitude' => 6.9214,
    'longitude' => 122.0790,
],

        ];

        foreach ($assets as $asset) {
            DB::table('assets')->insert(array_merge($asset, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}